import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pl' | 'fr' | 'it' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pl: {
    // Header
    'nav.products': 'Asortyment',
    'nav.about': 'O firmie',
    'nav.quality': 'Jakość',
    'nav.certificates': 'Certyfikaty',
    'nav.contact': 'Kontakt',
    'nav.download_price': 'Skontaktuj się',
    
    // Hero Section
    'hero.badge': 'Wiodący Eksporter w Polsce',
    'hero.title': 'Polski Drób',
    'hero.title_highlight': 'Najwyższej Jakości',
    'hero.description': 'Specjalizujemy się w eksporcie świeżego i mrożonego mięsa drobiowego. Dostarczamy produkty najwyższej jakości do największych sieci handlowych, zakładów przetwórczych i importerów w ponad 40 krajach świata.',
    'hero.cta_offer': 'Zapytaj o cenę',
    'hero.cta_phone': '+48 516 827 115',
    'hero.stats.years': 'lat doświadczenia',
    'hero.stats.countries': 'krajów eksportu',
    'hero.stats.tons': 'ton rocznie',
    'hero.stats.satisfaction': 'zadowolonych klientów',
    
    // Benefits Section
    'benefits.title': 'Dlaczego wybierają nas?',
    'benefits.subtitle': 'Jesteśmy liderem w eksporcie polskiego drobiu dzięki naszemu doświadczeniu i najwyższym standardom jakości',
    'benefits.quality.title': 'Pełna Kontrola Jakości',
    'benefits.quality.desc': 'Ścisła kontrola HACCP na każdym etapie produkcji. Własne laboratoria badawcze.',
    'benefits.delivery.title': 'Terminowość Dostaw',
    'benefits.delivery.desc': 'Gwarantujemy dostawy zgodnie z harmonogramem. Własna flota transportowa.',
    'benefits.team.title': 'Doświadczony Team',
    'benefits.team.desc': 'Zespół ekspertów z 20-letnim doświadczeniem w eksporcie drobiu.',
    'benefits.price.title': 'Konkurencyjne Ceny',
    'benefits.price.desc': 'Najlepsze ceny przy zachowaniu najwyższej jakości produktów.',
    
    // Products Section
    'products.title': 'Pełny Asortyment Drobiowy',
    'products.subtitle': 'Oferujemy kompletną gamę produktów drobiowych - od świeżego mięsa po produkty przetworzone. Wszystkie produkty pochodzą od certyfikowanych dostawców i są przetwarzane zgodnie z najwyższymi standardami UE.',
    'products.badge.fresh': 'Świeże mięso',
    'products.badge.frozen': 'Produkty mrożone',
    'products.badge.processed': 'Przetwory',
    'products.badge.private': 'Private label',
    
    // Product Cards
    'product.chicken_breast.title': 'Piersi z kurczaka bez kości',
    'product.chicken_breast.desc': 'Premium filety bez kości i skóry. Dostępne w różnych wagach: 140-200g, 200-300g, powyżej 300g. Pakowane próżniowo.',
    'product.chicken_wings.title': 'Skrzydełka kurczaka',
    'product.chicken_wings.desc': 'Świeże skrzydełka w różnych formatach: całe, 2-segmentowe, mid joints, drumettes. Różne kategorie wagowe.',
    'product.chicken_quarters.title': 'Ćwiartki kurczaka',
    'product.chicken_quarters.desc': 'Ćwiartki górne (skrzydło + pierś) i dolne (udo + podudzie). Idealne dla hurtowni i gastronomii.',
    'product.whole_chicken.title': 'Kurczak cały',
    'product.whole_chicken.desc': 'Kurczaki całe klasy A, waga 1000-2500g. Dostępne świeże i mrożone. Certyfikowane pochodzenie z polskich ferm.',
    'product.giblets.title': 'Podroby drobiowe',
    'product.giblets.desc': 'Wysokiej jakości podroby: serca, żołądki, wątróbki, szyje. Idealne do dalszego przetwórstwa.',
    'product.processed.title': 'Jajka',
    'product.processed.desc': 'Świeże jajka z certyfikowanych ferm, dostępne w różnych klasach i rozmiarach. Idealne do konsumpcji i przetwórstwa.',
    'product.carcasses.title': 'Tuszki drobiowe',
    'product.carcasses.desc': 'Świeże i mrożone tuszki drobiowe, różne wagi i pakowania. Idealne do dalszego przetwórstwa i eksportu.',
    'product.drumsticks.title': 'Podudzia',
    'product.drumsticks.desc': 'Podudzia z kurczaka klasy A, dostępne świeże i mrożone. Pakowane próżniowo lub MAP.',
    'product.cut_feet.title': 'Łapy cięte',
    'product.cut_feet.desc': 'Łapy drobiowe cięte i sortowane, eksportowane głównie na rynki azjatyckie. Pakowanie na zamówienie.',
    
    // Special Products
    'special.title': 'Specjalne Produkty na Zamówienie',
    'special.subtitle': 'Przygotowujemy produkty według indywidualnych specyfikacji klientów. Oferujemy usługi private label oraz packaging zgodny z wymaganiami rynków docelowych.',
    'special.production.title': 'Własne Linie Produkcyjne',
    'special.production.desc': 'Nowoczesne zakłady z certyfikatami EU',
    'special.private.title': 'Private Label',
    'special.private.desc': 'Produkty pod marką klienta',
    'special.export.title': 'Export Worldwide',
    'special.export.desc': 'Dostawy do 40+ krajów',
    'special.cta': 'Pobierz pełny katalog produktów (PDF)',
    
    // Quality Section
    'quality.title': 'Najwyższe Standardy Jakości',
    'quality.description': 'Nasza filozofia opiera się na bezwzględnym przestrzeganiu najwyższych standardów jakości i bezpieczeństwa żywności. Współpracujemy wyłącznie z certyfikowanymi farmami i zakładami, które spełniają surowe wymagania europejskie.',
    'quality.control.title': 'Kontrola na każdym etapie',
    'quality.control.desc': 'Od farmy do finalnego produktu - wielostopniowa kontrola jakości',
    'quality.lab.title': 'Własne laboratoria',
    'quality.lab.desc': 'Badania mikrobiologiczne i chemiczne w akredytowanych laboratoriach',
    'quality.cold.title': 'Chłodny łańcuch dostaw',
    'quality.cold.desc': 'Nieprzerwany łańcuch chłodniczy od uboju do klienta końcowego',
    'quality.trace.title': 'Śledzenie pochodzenia',
    'quality.trace.desc': 'Pełna traceability - od farmy do półki sklepowej',
    'quality.guarantee': '100% Bezpieczeństwo',
    'quality.guarantee.sub': 'Gwarancja najwyższej jakości',
    
    // Certifications
    'cert.title': 'Certyfikaty i Akredytacje',
    'cert.subtitle': 'Posiadamy wszystkie niezbędne certyfikaty i akredytacje wymagane do eksportu produktów drobiowych. Nasze zakłady są regularnie kontrolowane przez polskie i międzynarodowe organy certyfikujące.',
    'cert.haccp.desc': 'System analizy zagrożeń i krytycznych punktów kontroli zgodny z wymogami UE',
    'cert.iso.desc': 'Międzynarodowy standard systemu zarządzania bezpieczeństwem żywności',
    'cert.gap.desc': 'Globalne standardy dobrej praktyki rolniczej i hodowlanej',
    'cert.ifs.desc': 'International Featured Standards dla bezpieczeństwa i jakości żywności',
    'cert.additional.title': 'Dodatkowe Certyfikaty Eksportowe',
    'cert.vet.title': 'Certyfikat Weterynaryjny',
    'cert.vet.desc': 'Wydawany przez PIW dla każdej partii eksportowej',
    'cert.halal.title': 'Halal Certification',
    'cert.halal.desc': 'Certyfikacja dla rynków muzułmańskich',
    'cert.eu.title': 'EU Health Certificate',
    'cert.eu.desc': 'Certyfikat zdrowia dla eksportu w ramach UE',
    
    // About Section
    'about.title': 'Lider Eksportu Polskiego Drobiu',
    'about.description1': 'Masovia Poultry to wiodący eksporter polskiego drobiu z ponad 20-letnim doświadczeniem na rynku międzynarodowym. Jesteśmy dumni z tego, że polski drób cieszy się uznaniem na całym świecie dzięki naszej pracy i zaangażowaniu.',
    'about.description2': 'Współpracujemy z największymi sieciami handlowymi w Europie, Azji i na Bliskim Wschodzie. Nasze produkty trafiają do sklepów w Niemczech, Francji, Wielkiej Brytanii, Holandii, krajach Bałkańskich oraz na rynki azjatyckie.',
    'about.stats.tons': 'ton rocznie',
    'about.stats.countries': 'krajów eksportu',
    'about.stats.clients': 'zadowolonych klientów',
    'about.stats.delivery': 'punktualność dostaw',
    'about.cta': 'Poznaj naszą historię',
    'about.company': 'Masovia Poultry',
    'about.tagline': 'Polski drób premium od 2004',
    'about.subtitle': 'Eksport do całego świata',
    
    // Contact Section
    'contact.title': 'Rozpocznij Współpracę',
    'contact.subtitle': 'Skontaktuj się z nami już dziś i otrzymaj spersonalizowaną ofertę dostosowaną do Twoich potrzeb. Nasz zespół ekspertów odpowie na wszystkie pytania i pomoże wybrać najlepsze produkty.',
    'contact.badge.response': 'Odpowiedź w 24h',
    'contact.badge.samples': 'Darmowe próbki',
    'contact.badge.prices': 'Konkurencyjne ceny',
    'contact.info.title': 'Dane kontaktowe',
    'contact.phone.title': 'Telefon',
    'contact.phone.export': '+48 516 827 115 (Export Manager)',
    'contact.phone.sales': '+48 987 654 321 (Sales Director)',
    'contact.email.title': 'Email',
    'contact.address.title': 'Siedziba główna',
    'contact.address.street': 'ul. Przemysłowa 15',
    'contact.address.city': '05-800 Pruszków, Polska',
    'contact.hours.title': 'Godziny pracy',
    'contact.hours.weekdays': 'Poniedziałek - Piątek: 8:00 - 18:00',
    'contact.hours.saturday': 'Sobota: 9:00 - 14:00',
    'contact.hours.sunday': 'Niedziela: Zamknięte',
    'contact.hours.urgent': 'W przypadku pilnych spraw eksportowych jesteśmy dostępni 24/7',
    
    // CTA Section
    'cta.title': 'Dołącz do Grona Naszych Partnerów',
    'cta.subtitle': 'Współpracujemy z największymi importerami, sieciami handlowymi i zakładami przetwórczymi w Europie. Polski drób premium to gwarancja sukcesu na Twoim rynku.',
    'cta.tesco': 'Sieć handlowa - UK',
    'cta.auchan': 'Hipermarkety - Europa',
    'cta.metro': 'Cash & Carry - EMEA',
    'cta.special_offer': 'Otrzymaj ofertę specjalną',
    'cta.meeting': 'Umów spotkanie biznesowe',
    
    // Footer
    'footer.tagline': 'Wiodący eksporter najwyższej jakości polskiego drobiu na rynki międzynarodowe.',
    'footer.company_info': 'Polski drób premium od 2004',
    'footer.products.title': 'Produkty',
    'footer.products.breast': 'Piersi z kurczaka',
    'footer.products.wings': 'Skrzydełka kurczaka',
    'footer.products.quarters': 'Ćwiartki kurczaka',
    'footer.products.whole': 'Kurczak cały',
    'footer.products.giblets': 'Podroby drobiowe',
    'footer.products.processed': 'Produkty przetworzone',
    'footer.company.title': 'Firma',
    'footer.company.about': 'O nas',
    'footer.company.history': 'Historia firmy',
    'footer.company.certificates': 'Certyfikaty jakości',
    'footer.company.farms': 'Nasze farmy',
    'footer.company.career': 'Kariera',
    'footer.company.news': 'Aktualności',
    'footer.contact.title': 'Kontakt',
    'footer.copyright': '© 2024 Masovia Poultry. Wszystkie prawa zastrzeżone. | Polski drób premium | Eksport worldwide',

    // Product Features
    'product.whole_chicken.feature1': 'Waga 1-2.5kg',
    'product.whole_chicken.feature2': 'Klasa A premium',
    'product.whole_chicken.feature3': 'Własne farmy',
    'product.whole_chicken.feature4': 'Certyfikat pochodzenia',
    'product.carcasses.feature1': 'Świeże i mrożone tuszki',
    'product.carcasses.feature2': 'Różne wagi',
    'product.carcasses.feature3': 'Pakowanie próżniowe',
    'product.carcasses.feature4': 'Certyfikowane pochodzenie',
    'product.processed.feature1': 'Świeże jajka',
    'product.processed.feature2': 'Różne klasy i rozmiary',
    'product.processed.feature3': 'Certyfikowane fermy',
    'product.processed.feature4': 'Idealne do konsumpcji i przetwórstwa',
    'product.chicken_breast.feature1': 'Bez antybiotyków',
    'product.chicken_breast.feature2': 'Klasa A',
    'product.chicken_breast.feature3': 'Pakowanie próżniowe',
    'product.chicken_breast.feature4': 'Najwyższa jakość',
    'product.drumsticks.feature1': 'Podudzia z kurczaka klasy A',
    'product.drumsticks.feature2': 'Pakowanie MAP',
    'product.drumsticks.feature3': 'Dostępne świeże i mrożone',
    'product.drumsticks.feature4': 'Różne gramatury',
    'product.chicken_quarters.feature1': 'Górne i dolne',
    'product.chicken_quarters.feature2': 'Różne wagi',
    'product.chicken_quarters.feature3': 'Opakowanie MAP',
    'product.chicken_quarters.feature4': 'Długa trwałość',
    'product.chicken_wings.feature1': 'Różne cięcia',
    'product.chicken_wings.feature2': 'Świeże i mrożone',
    'product.chicken_wings.feature3': 'Opakowania od 1kg do 15kg',
    'product.chicken_wings.feature4': 'Różne gramatury',
    'product.giblets.feature1': 'Serca, żołądki, wątróbki',
    'product.giblets.feature2': 'Świeże i mrożone',
    'product.giblets.feature3': 'Kontrola weterynaryjna',
    'product.giblets.feature4': 'Pakowanie na zamówienie',
    'product.cut_feet.feature1': 'Łapy cięte i sortowane',
    'product.cut_feet.feature2': 'Idealne do przetwórstwa',
    'product.cut_feet.feature3': 'Pakowanie na zamówienie',
    'product.cut_feet.feature4': 'Świeże i mrożone',
  },
  fr: {
    // Header
    'nav.products': 'Assortiment',
    'nav.about': 'À propos',
    'nav.quality': 'Qualité',
    'nav.certificates': 'Certificats',
    'nav.contact': 'Contact',
    'nav.download_price': 'Contactez-nous',
    
    // Hero Section
    'hero.badge': 'Exportateur leader en Pologne',
    'hero.title': 'Volaille polonaise',
    'hero.title_highlight': 'De la plus haute qualité',
    'hero.description': 'Nous sommes spécialisés dans l\'exportation de viande de volaille fraîche et surgelée. Nous fournissons des produits de la plus haute qualité aux plus grandes chaînes de distribution, usines et importateurs dans plus de 40 pays à travers le monde.',
    'hero.cta_offer': 'Demander un prix',
    'hero.cta_phone': '+48 516 827 115',
    'hero.stats.years': 'années d\'expérience',
    'hero.stats.countries': 'pays d\'exportation',
    'hero.stats.tons': 'tonnes par an',
    'hero.stats.satisfaction': 'clients satisfaits',
    
    // Benefits Section
    'benefits.title': 'Pourquoi nous choisir ?',
    'benefits.subtitle': 'Nous sommes leader dans l\'exportation de volaille polonaise grâce à notre expérience et aux plus hauts standards de qualité',
    'benefits.quality.title': 'Contrôle Qualité Complet',
    'benefits.quality.desc': 'Contrôle HACCP strict à chaque étape de production. Laboratoires de recherche propres.',
    'benefits.delivery.title': 'Ponctualité des Livraisons',
    'benefits.delivery.desc': 'Nous garantissons les livraisons selon le calendrier. Flotte de transport propre.',
    'benefits.team.title': 'Équipe Expérimentée',
    'benefits.team.desc': 'Équipe d\'experts avec 20 ans d\'expérience dans l\'exportation de volaille.',
    'benefits.price.title': 'Prix Compétitifs',
    'benefits.price.desc': 'Les meilleurs prix tout en maintenant la plus haute qualité des produits.',
    
    // Products Section
    'products.title': 'Assortiment Complet de Volaille',
    'products.subtitle': 'Nous offrons une gamme complète de produits de volaille - de la viande fraîche aux produits transformés. Tous les produits proviennent de fournisseurs certifiés et sont transformés selon les plus hauts standards UE.',
    'products.badge.fresh': 'Viande fraîche',
    'products.badge.frozen': 'Produits surgelés',
    'products.badge.processed': 'Transformés',
    'products.badge.private': 'Marque privée',
    
    // Product Cards
    'product.chicken_breast.title': 'Filets de poulet désossés',
    'product.chicken_breast.desc': 'Filets premium sans os ni peau. Disponibles en différents poids : 140-200g, 200-300g, plus de 300g. Emballage sous vide.',
    'product.chicken_wings.title': 'Ailes de poulet',
    'product.chicken_wings.desc': 'Ailes fraîches en différents formats : entières, 2 segments, mid joints, pilons. Différentes catégories de poids.',
    'product.chicken_quarters.title': 'Quartiers de poulet',
    'product.chicken_quarters.desc': 'Quartiers supérieurs (aile + blanc) et inférieurs (cuisse + pilon). Idéaux pour grossistes et restauration.',
    'product.whole_chicken.title': 'Poulet entier',
    'product.whole_chicken.desc': 'Poulets entiers classe A, poids 1000-2500g. Disponibles frais et surgelés. Origine certifiée des fermes polonaises.',
    'product.giblets.title': 'Abats de volaille',
    'product.giblets.desc': 'Abats de haute qualité : cœurs, gésiers, foies, cous. Idéaux pour transformation ultérieure.',
    'product.processed.title': 'Oeufs',
    'product.processed.desc': 'Oeufs frais provenant de fermes certifiées, disponibles en différentes classes et tailles. Idéals pour la consommation et la transformation.',
    'product.carcasses.title': 'Carcasses de volaille',
    'product.carcasses.desc': 'Carcasses fraîches et surgelées, différents poids et conditionnements. Idéales pour transformation et export.',
    'product.drumsticks.title': 'Pilons',
    'product.drumsticks.desc': 'Pilons de poulet de classe A, disponibles frais et surgelés. Conditionnement sous vide ou MAP.',
    'product.cut_feet.title': 'Pattes coupées',
    'product.cut_feet.desc': 'Pattes de volaille coupées et triées, principalement exportées vers l\'Asie. Conditionnement sur demande.',
    
    // Special Products
    'special.title': 'Produits Spéciaux sur Commande',
    'special.subtitle': 'Nous préparons des produits selon les spécifications individuelles des clients. Nous offrons des services de marque privée et emballage conforme aux exigences des marchés cibles.',
    'special.production.title': 'Lignes de Production Propres',
    'special.production.desc': 'Installations modernes avec certificats UE',
    'special.private.title': 'Marque Privée',
    'special.private.desc': 'Produits sous marque client',
    'special.export.title': 'Export Mondial',
    'special.export.desc': 'Livraisons vers 40+ pays',
    'special.cta': 'Télécharger le catalogue complet des produits (PDF)',
    
    // Quality Section
    'quality.title': 'Standards de Qualité les Plus Élevés',
    'quality.description': 'Notre philosophie repose sur le respect absolu des plus hauts standards de qualité et de sécurité alimentaire. Nous collaborons exclusivement avec des fermes et installations certifiées qui répondent aux exigences européennes strictes.',
    'quality.control.title': 'Contrôle à chaque étape',
    'quality.control.desc': 'De la ferme au produit final - contrôle qualité multi-niveaux',
    'quality.lab.title': 'Laboratoires propres',
    'quality.lab.desc': 'Tests microbiologiques et chimiques dans des laboratoires accrédités',
    'quality.cold.title': 'Chaîne du froid',
    'quality.cold.desc': 'Chaîne du froid ininterrompue de l\'abattage au client final',
    'quality.trace.title': 'Traçabilité d\'origine',
    'quality.trace.desc': 'Traçabilité complète - de la ferme au rayon du magasin',
    'quality.guarantee': '100% Sécurité',
    'quality.guarantee.sub': 'Garantie de la plus haute qualité',
    
    // Certifications
    'cert.title': 'Certificats et Accréditations',
    'cert.subtitle': 'Nous possédons tous les certificats et accréditations nécessaires requis pour l\'exportation de produits de volaille. Nos installations sont régulièrement contrôlées par des organismes de certification polonais et internationaux.',
    'cert.haccp.desc': 'Système d\'analyse des dangers et points critiques de contrôle conforme aux exigences UE',
    'cert.iso.desc': 'Standard international du système de gestion de la sécurité alimentaire',
    'cert.gap.desc': 'Standards globaux de bonnes pratiques agricoles et d\'élevage',
    'cert.ifs.desc': 'International Featured Standards pour la sécurité et qualité alimentaire',
    'cert.additional.title': 'Certificats d\'Exportation Supplémentaires',
    'cert.vet.title': 'Certificat Vétérinaire',
    'cert.vet.desc': 'Délivré par PIW pour chaque lot d\'exportation',
    'cert.halal.title': 'Certification Halal',
    'cert.halal.desc': 'Certification pour les marchés musulmans',
    'cert.eu.title': 'Certificat Sanitaire UE',
    'cert.eu.desc': 'Certificat de santé pour l\'exportation dans l\'UE',
    
    // About Section
    'about.title': 'Leader de l\'Exportation de Volaille Polonaise',
    'about.description1': 'Masovia Poultry est un exportateur leader de volaille polonaise avec plus de 20 ans d\'expérience sur le marché international. Nous sommes fiers que la volaille polonaise soit reconnue dans le monde entier grâce à notre travail et engagement.',
    'about.description2': 'Nous collaborons avec les plus grandes chaînes de distribution en Europe, Asie et au Moyen-Orient. Nos produits arrivent dans les magasins en Allemagne, France, Grande-Bretagne, Pays-Bas, pays des Balkans et sur les marchés asiatiques.',
    'about.stats.tons': 'tonnes par an',
    'about.stats.countries': 'pays d\'exportation',
    'about.stats.clients': 'clients satisfaits',
    'about.stats.delivery': 'ponctualité des livraisons',
    'about.cta': 'Découvrez notre histoire',
    'about.company': 'Masovia Poultry',
    'about.tagline': 'Volaille polonaise premium depuis 2004',
    'about.subtitle': 'Export vers le monde entier',
    
    // Contact Section
    'contact.title': 'Commencez la Collaboration',
    'contact.subtitle': 'Contactez-nous dès aujourd\'hui et recevez une offre personnalisée adaptée à vos besoins. Notre équipe d\'experts répondra à toutes vos questions et vous aidera à choisir les meilleurs produits.',
    'contact.badge.response': 'Réponse en 24h',
    'contact.badge.samples': 'Échantillons gratuits',
    'contact.badge.prices': 'Prix compétitifs',
    'contact.info.title': 'Coordonnées',
    'contact.phone.title': 'Téléphone',
    'contact.phone.export': '+48 516 827 115 (Responsable Export)',
    'contact.phone.sales': '+48 987 654 321 (Directeur Commercial)',
    'contact.email.title': 'Email',
    'contact.address.title': 'Siège social',
    'contact.address.street': 'ul. Przemysłowa 15',
    'contact.address.city': '05-800 Pruszków, Pologne',
    'contact.hours.title': 'Heures d\'ouverture',
    'contact.hours.weekdays': 'Lundi - Vendredi : 8h00 - 18h00',
    'contact.hours.saturday': 'Samedi : 9:00 - 14:00',
    'contact.hours.sunday': 'Dimanche : Fermé',
    'contact.hours.urgent': 'Pour les affaires d\'exportation urgentes, nous sommes disponibles 24h/24 7j/7',
    
    // CTA Section
    'cta.title': 'Rejoignez le Cercle de Nos Partenaires',
    'cta.subtitle': 'Nous collaborons avec les plus grands importateurs, chaînes de distribution et entreprises de transformation en Europe. La volaille polonaise premium est une garantie de succès sur votre marché.',
    'cta.tesco': 'Chaîne de distribution - UK',
    'cta.auchan': 'Hypermarchés - Europe',
    'cta.metro': 'Cash & Carry - EMEA',
    'cta.special_offer': 'Recevoir une offre spéciale',
    'cta.meeting': 'Planifier un rendez-vous d\'affaires',
    
    // Footer
    'footer.tagline': 'Exportateur leader de volaille polonaise de la plus haute qualité vers les marchés internationaux.',
    'footer.company_info': 'Volaille polonaise premium depuis 2004',
    'footer.products.title': 'Produits',
    'footer.products.breast': 'Filets de poulet',
    'footer.products.wings': 'Ailes de poulet',
    'footer.products.quarters': 'Quartiers de poulet',
    'footer.products.whole': 'Poulet entier',
    'footer.products.giblets': 'Abats de volaille',
    'footer.products.processed': 'Produits transformés',
    'footer.company.title': 'Entreprise',
    'footer.company.about': 'À propos',
    'footer.company.history': 'Histoire de l\'entreprise',
    'footer.company.certificates': 'Certificats qualité',
    'footer.company.farms': 'Nos fermes',
    'footer.company.career': 'Carrière',
    'footer.company.news': 'Actualités',
    'footer.contact.title': 'Contact',
    'footer.copyright': '© 2024 Masovia Poultry. Tous droits réservés. | Volaille polonaise premium | Export mondial',

    // Product Features
    'product.whole_chicken.feature1': 'Poids 1-2,5kg',
    'product.whole_chicken.feature2': 'Classe A premium',
    'product.whole_chicken.feature3': 'Fermes propres',
    'product.whole_chicken.feature4': "Certificat d'origine",
    'product.carcasses.feature1': 'Carcasses fraîches et surgelées',
    'product.carcasses.feature2': 'Différents poids',
    'product.carcasses.feature3': 'Emballage sous vide',
    'product.carcasses.feature4': 'Origine certifiée',
    'product.processed.feature1': 'Œufs frais',
    'product.processed.feature2': 'Différentes classes et tailles',
    'product.processed.feature3': 'Fermes certifiées',
    'product.processed.feature4': 'Idéal pour consommation et transformation',
    'product.chicken_breast.feature1': 'Sans antibiotiques',
    'product.chicken_breast.feature2': 'Classe A',
    'product.chicken_breast.feature3': 'Emballage sous vide',
    'product.chicken_breast.feature4': 'Qualité supérieure',
    'product.chicken_wings.feature1': 'Différentes découpes',
    'product.chicken_wings.feature2': 'Fraîches et surgelées',
    'product.chicken_wings.feature3': 'Emballages de 1kg à 15kg',
    'product.chicken_wings.feature4': 'Différents grammages',
    'product.chicken_quarters.feature1': 'Supérieures et inférieures',
    'product.chicken_quarters.feature2': 'Différents poids',
    'product.chicken_quarters.feature3': 'Emballage MAP',
    'product.chicken_quarters.feature4': 'Longue conservation',
    'product.whole_chicken.feature1': 'Poids 1-2,5kg',
    'product.whole_chicken.feature2': 'Classe A premium',
    'product.whole_chicken.feature3': 'Fermes propres',
    'product.whole_chicken.feature4': "Certificat d'origine",
    'product.giblets.feature1': 'Cœurs, gésiers, foies',
    'product.giblets.feature2': 'Frais et surgelés',
    'product.giblets.feature3': 'Contrôle vétérinaire',
    'product.giblets.feature4': 'Emballage sur demande',
    'product.processed.feature1': 'Œufs frais',
    'product.processed.feature2': 'Différentes classes et tailles',
    'product.processed.feature3': 'Fermes certifiées',
    'product.processed.feature4': 'Idéal pour consommation et transformation',
    'product.carcasses.feature1': 'Carcasses fraîches et surgelées',
    'product.carcasses.feature2': 'Différents poids',
    'product.carcasses.feature3': 'Emballage sous vide',
    'product.carcasses.feature4': 'Origine certifiée',
    'product.drumsticks.feature1': 'Pilons de poulet classe A',
    'product.drumsticks.feature2': 'Emballage MAP',
    'product.drumsticks.feature3': 'Disponibles frais et surgelés',
    'product.drumsticks.feature4': 'Différents grammages',
    'product.cut_feet.feature1': 'Pattes coupées et triées',
    'product.cut_feet.feature2': 'Idéales pour la transformation',
    'product.cut_feet.feature3': 'Emballage sur demande',
    'product.cut_feet.feature4': 'Fraîches et surgelées',
  },
  it: {
    // Header
    'nav.products': 'Assortimento',
    'nav.about': 'Chi siamo',
    'nav.quality': 'Qualità',
    'nav.certificates': 'Certificati',
    'nav.contact': 'Contatto',
    'nav.download_price': 'Contattaci',

    // Hero Section
    'hero.badge': 'Leader Esportatore in Polonia',
    'hero.title': 'Pollame Polacco',
    'hero.title_highlight': 'Di Qualità Superiore',
    'hero.description': 'Siamo specializzati nell\'esportazione di carne di pollame fresca e congelata. Forniamo prodotti di altissima qualità alle principali catene di distribuzione, aziende di trasformazione e importatori in oltre 40 paesi.',
    'hero.cta_offer': 'Richiedi un prezzo',
    'hero.cta_phone': '+48 516 827 115',
    'hero.stats.years': 'anni di esperienza',
    'hero.stats.countries': 'paesi di esportazione',
    'hero.stats.tons': 'tonnellate all\'anno',
    'hero.stats.satisfaction': 'clienti soddisfatti',

    // Benefits Section
    'benefits.title': 'Perché sceglierci?',
    'benefits.subtitle': 'Siamo leader nell\'esportazione di pollame polacco grazie alla nostra esperienza e ai più alti standard di qualità',
    'benefits.quality.title': 'Controllo Qualità Totale',
    'benefits.quality.desc': 'Controllo HACCP rigoroso in ogni fase della produzione. Laboratori propri.',
    'benefits.delivery.title': 'Puntualità delle Consegne',
    'benefits.delivery.desc': 'Garantiamo consegne secondo programma. Flotta di trasporto propria.',
    'benefits.team.title': 'Team Esperto',
    'benefits.team.desc': 'Team di esperti con 20 anni di esperienza nell\'esportazione di pollame.',
    'benefits.price.title': 'Prezzi Competitivi',
    'benefits.price.desc': 'I migliori prezzi mantenendo la massima qualità dei prodotti.',

    // Products Section
    'products.title': 'Assortimento Completo di Pollame',
    'products.subtitle': 'Offriamo una gamma completa di prodotti avicoli - dalla carne fresca ai prodotti trasformati. Tutti i prodotti provengono da fornitori certificati e sono lavorati secondo i più alti standard UE.',
    'products.badge.fresh': 'Carne fresca',
    'products.badge.frozen': 'Prodotti surgelati',
    'products.badge.processed': 'Trasformati',
    'products.badge.private': 'Private label',

    // Product Cards
    'product.chicken_breast.title': 'Petto di pollo disossato',
    'product.chicken_breast.desc': 'Filetti premium senza ossa né pelle. Disponibili in vari pesi: 140-200g, 200-300g, oltre 300g. Vacuum packed.',
    'product.chicken_wings.title': 'Alette di pollo',
    'product.chicken_wings.desc': 'Alette fresche in diversi formati: intere, 2 segmenti, mid joints, drumettes. Diverse categorie di peso.',
    'product.chicken_quarters.title': 'Quartini di pollo',
    'product.chicken_quarters.desc': 'Quartini superiori (ala + petto) e inferiori (coscia + fuso). Ideali per grossisti e ristorazione.',
    'product.whole_chicken.title': 'Pollo intero',
    'product.whole_chicken.desc': 'Polli interi classe A, peso 1000-2500g. Disponibili freschi e surgelati. Origine certificata da allevamenti polacchi.',
    'product.giblets.title': 'Frattaglie di pollame',
    'product.giblets.desc': 'Frattaglie di alta qualità: cuori, ventrigli, fegati, colli. Ideal for ulteriore trasformazione.',
    'product.processed.title': 'Uova',
    'product.processed.desc': 'Uova fresche da allevamenti certificati, disponibili in diverse classi e dimensioni. Ideal for consumption and processing.',
    'product.carcasses.title': 'Carcasse di pollame',
    'product.carcasses.desc': 'Carcasse fresche e surgelate, diversi pesi e confezioni. Ideal for further processing and export.',
    'product.drumsticks.title': 'Fusi di pollo',
    'product.drumsticks.desc': 'Fusi di pollo classe A, disponibili freschi e surgelati. Confezionati sottovuoto o MAP.',
    'product.cut_feet.title': 'Zampe tagliate',
    'product.cut_feet.desc': 'Zampe di pollame tagliate e selezionate, esportate principalmente in Asia. Confezionamento su richiesta.',

    // Special Products
    'special.title': 'Prodotti Speciali su Richiesta',
    'special.subtitle': 'Prepariamo prodotti secondo le specifiche individuali dei clienti. Offriamo servizi di private label e packaging conforme ai requisiti dei mercati di destinazione.',
    'special.production.title': 'Linee di Produzione Proprie',
    'special.production.desc': 'Stabilimenti moderni con certificazioni UE',
    'special.private.title': 'Private Label',
    'special.private.desc': 'Prodotti a marchio del cliente',
    'special.export.title': 'Export Mondiale',
    'special.export.desc': 'Consegne in oltre 40 paesi',
    'special.cta': 'Scarica il catalogo completo dei prodotti (PDF)',

    // Quality Section
    'quality.title': 'Standard di Qualità Più Elevati',
    'quality.description': 'La nostra filosofia si basa sul rispetto assoluto dei più alti standard di qualità e sicurezza alimentare. Collaboriamo solo con allevamenti e stabilimenti certificati che soddisfano i rigorosi requisiti europei.',
    'quality.control.title': 'Controllo a ogni fase',
    'quality.control.desc': 'Dalla fattoria al prodotto finale - controllo qualità multilivello',
    'quality.lab.title': 'Laboratori propri',
    'quality.lab.desc': 'Analisi microbiologiche e chimiche in laboratori accreditati',
    'quality.cold.title': 'Catena del freddo',
    'quality.cold.desc': 'Catena del freddo ininterrotta dalla macellazione al cliente finale',
    'quality.trace.title': 'Tracciabilità dell\'origine',
    'quality.trace.desc': 'Tracciabilità completa - dalla fattoria allo scaffale',
    'quality.guarantee': '100% Sicurezza',
    'quality.guarantee.sub': 'Garanzia della massima qualità',

    // Certifications
    'cert.title': 'Certificati e Accreditamenti',
    'cert.subtitle': 'Abbiamo tutti i certificati e le accreditamenti necessari per l\'esportazione di prodotti avicoli. I nostri stabilimenti sono regolarmente controllati da enti certificatori polacchi e internazionali.',
    'cert.haccp.desc': 'Sistema di analisi dei rischi e punti critici di controllo conforme ai requisiti UE',
    'cert.iso.desc': 'Standard internazionale per la gestione della sicurezza alimentare',
    'cert.gap.desc': 'Standard globali di buone pratiche agricole e di allevamento',
    'cert.ifs.desc': 'International Featured Standards per la sicurezza e qualità alimentare',
    'cert.additional.title': 'Certificati Export Supplementari',
    'cert.vet.title': 'Certificato Veterinario',
    'cert.vet.desc': 'Rilasciato da PIW per ogni lotto export',
    'cert.halal.title': 'Certificazione Halal',
    'cert.halal.desc': 'Certification for Muslim markets',
    'cert.eu.title': 'Certificato Sanitario UE',
    'cert.eu.desc': 'Certificato sanitario per export UE',

    // About Section
    'about.title': 'Leader nell\'Export di Pollame Polacco',
    'about.description1': 'Masovia Poultry è un esportatore leader di pollame polacco con oltre 20 anni d\'esperienza sul mercato internazionale. Siamo orgogliosi che il pollame polacco sia riconosciuto in tutto il mondo grazie al nostro lavoro e impegno.',
    'about.description2': 'Collaboriamo con le principali catene di distribuzione in Europa, Asia e Medio Oriente. I nostri prodotti arrivano nei negozi in Germania, Francia, Regno Unito, Paesi Bassi, paesi balcanici e mercati asiatici.',
    'about.stats.tons': 'tonnellate all\'anno',
    'about.stats.countries': 'paesi di esportazione',
    'about.stats.clients': 'clienti soddisfatti',
    'about.stats.delivery': 'puntualità delle consegne',
    'about.cta': 'Scopri la nostra storia',
    'about.company': 'Masovia Poultry',
    'about.tagline': 'Pollame polacco premium dal 2004',
    'about.subtitle': 'Export in tutto il mondo',

    // Contact Section
    'contact.title': 'Inizia la Collaborazione',
    'contact.subtitle': 'Contattaci oggi stesso e ricevi un\'offerta personalizzata su misura per le tue esigenze. Il nostro team di esperti risponderà a tutte le domande e ti aiuterà a scegliere i prodotti migliori.',
    'contact.badge.response': 'Risposta entro 24h',
    'contact.badge.samples': 'Campioni gratuiti',
    'contact.badge.prices': 'Prezzi competitivi',
    'contact.info.title': 'Dati di contatto',
    'contact.phone.title': 'Telefono',
    'contact.phone.export': '+48 516 827 115 (Export Manager)',
    'contact.phone.sales': '+48 987 654 321 (Direttore Vendite)',
    'contact.email.title': 'Email',
    'contact.address.title': 'Sede principale',
    'contact.address.street': 'ul. Przemysłowa 15',
    'contact.address.city': '05-800 Pruszków, Polonia',
    'contact.hours.title': 'Orari di lavoro',
    'contact.hours.weekdays': 'Monday - Friday: 8:00 - 18:00',
    'contact.hours.saturday': 'Saturday: 9:00 - 14:00',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.hours.urgent': 'For urgent export matters, we are available 24/7',

    // CTA Section
    'cta.title': 'Unisciti ai Nostri Partner',
    'cta.subtitle': 'Collaboriamo con i maggiori importatori, catene di distribuzione e aziende di trasformazione in Europa. Il pollame polacco premium è garanzia di successo sul tuo mercato.',
    'cta.tesco': 'Catena distributiva - UK',
    'cta.auchan': 'Ipermercati - Europa',
    'cta.metro': 'Cash & Carry - EMEA',
    'cta.special_offer': 'Ricevi un\'offerta speciale',
    'cta.meeting': 'Fissa un incontro d\'affari',

    // Footer
    'footer.tagline': 'Leader nell\'esportazione di pollame polacco di altissima qualità sui mercati internazionali.',
    'footer.company_info': 'Pollame polacco premium dal 2004',
    'footer.products.title': 'Prodotti',
    'footer.products.breast': 'Petto di pollo',
    'footer.products.wings': 'Alette di pollo',
    'footer.products.quarters': 'Quartini di pollo',
    'footer.products.whole': 'Pollo intero',
    'footer.products.giblets': 'Frattaglie di pollame',
    'footer.products.processed': 'Uova',
    'footer.company.title': 'Azienda',
    'footer.company.about': 'Chi siamo',
    'footer.company.history': 'Storia aziendale',
    'footer.company.certificates': 'Certificati di qualità',
    'footer.company.farms': 'I nostri allevamenti',
    'footer.company.career': 'Carriera',
    'footer.company.news': 'Novità',
    'footer.contact.title': 'Contatto',
    'footer.copyright': '© 2024 Masovia Poultry. Tutti i diritti riservati. | Polish premium poultry | Export worldwide',

    // Product Features
    'product.whole_chicken.feature1': 'Peso 1-2.5kg',
    'product.whole_chicken.feature2': 'Classe A premium',
    'product.whole_chicken.feature3': 'Allevamenti propri',
    'product.whole_chicken.feature4': 'Certificato di origine',
    'product.carcasses.feature1': 'Carcasse fresche e surgelate',
    'product.carcasses.feature2': 'Vari pesi',
    'product.carcasses.feature3': 'Confezionamento sottovuoto',
    'product.carcasses.feature4': 'Origine certificata',
    'product.processed.feature1': 'Uova fresche',
    'product.processed.feature2': 'Diverse classi e dimensioni',
    'product.processed.feature3': 'Allevamenti certificati',
    'product.processed.feature4': 'Ideali per consumo e trasformazione',
    'product.chicken_breast.feature1': 'Senza antibiotici',
    'product.chicken_breast.feature2': 'Classe A',
    'product.chicken_breast.feature3': 'Confezionamento sottovuoto',
    'product.chicken_breast.feature4': 'Shelf life 10 giorni',
    'product.drumsticks.feature1': 'Fusi di pollo classe A',
    'product.drumsticks.feature2': 'Confezionamento MAP',
    'product.drumsticks.feature3': 'Disponibili freschi e surgelati',
    'product.drumsticks.feature4': 'Vari grammature',
    'product.chicken_quarters.feature1': 'Superiori e inferiori',
    'product.chicken_quarters.feature2': 'Vari pesi',
    'product.chicken_quarters.feature3': 'Confezionamento MAP',
    'product.chicken_quarters.feature4': 'Lunga conservazione',
    'product.chicken_wings.feature1': 'Tagli diversi',
    'product.chicken_wings.feature2': 'Fresche e surgelate',
    'product.chicken_wings.feature3': 'Confezioni da 1kg a 15kg',
    'product.chicken_wings.feature4': 'Qualità export',
    'product.giblets.feature1': 'Cuori, ventrigli, fegati',
    'product.giblets.feature2': 'Freschi e surgelati',
    'product.giblets.feature3': 'Controllo veterinario',
    'product.giblets.feature4': 'Confezionamento su richiesta',
    'product.cut_feet.feature1': 'Zampe tagliate e selezionate',
    'product.cut_feet.feature2': 'Ideali per la trasformazione',
    'product.cut_feet.feature3': 'Confezionamento su richiesta',
    'product.cut_feet.feature4': 'Fresche e surgelate',
  },
  en: {
    // Header
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.quality': 'Quality',
    'nav.certificates': 'Certificates',
    'nav.contact': 'Contact',
    'nav.download_price': 'Contact us',
    
    // Hero Section
    'hero.badge': 'Leading Exporter in Poland',
    'hero.title': 'Polish Poultry',
    'hero.title_highlight': 'Top Quality',
    'hero.description': 'We specialize in exporting fresh and frozen poultry meat. We deliver the highest quality products to the largest retail chains, processing plants, and importers in over 40 countries worldwide.',
    'hero.cta_offer': 'Request a price',
    'hero.cta_phone': '+48 516 827 115',
    'hero.stats.years': 'years of experience',
    'hero.stats.countries': 'export countries',
    'hero.stats.tons': 'tons per year',
    'hero.stats.satisfaction': 'satisfied clients',
    
    // Benefits Section
    'benefits.title': 'Why choose us?',
    'benefits.subtitle': 'We are a leader in Polish poultry export thanks to our experience and the highest quality standards',
    'benefits.quality.title': 'Total Quality Control',
    'benefits.quality.desc': 'Strict HACCP control at every stage of production. Own research laboratories.',
    'benefits.delivery.title': 'On-time Deliveries',
    'benefits.delivery.desc': 'We guarantee deliveries according to schedule. Own transport fleet.',
    'benefits.team.title': 'Experienced Team',
    'benefits.team.desc': 'A team of experts with 20 years of experience in poultry export.',
    'benefits.price.title': 'Competitive Prices',
    'benefits.price.desc': 'The best prices while maintaining the highest product quality.',
    
    // Products Section
    'products.title': 'Full Poultry Assortment',
    'products.subtitle': 'We offer a complete range of poultry products - from fresh meat to processed products. All products come from certified suppliers and are processed according to the highest EU standards.',
    'products.badge.fresh': 'Fresh meat',
    'products.badge.frozen': 'Frozen products',
    'products.badge.processed': 'Processed',
    'products.badge.private': 'Private label',
    
    // Product Cards
    'product.chicken_breast.title': 'Boneless chicken breast',
    'product.chicken_breast.desc': 'Premium fillets without bones or skin. Available in various weights: 140-200g, 200-300g, over 300g. Vacuum packed.',
    'product.chicken_wings.title': 'Chicken wings',
    'product.chicken_wings.desc': 'Fresh wings in various formats: whole, 2-segment, mid joints, drumettes. Different weight categories.',
    'product.chicken_quarters.title': 'Chicken quarters',
    'product.chicken_quarters.desc': 'Upper quarters (wing + breast) and lower (thigh + drumstick). Ideal for wholesalers and gastronomy.',
    'product.whole_chicken.title': 'Whole chicken',
    'product.whole_chicken.desc': 'Whole class A chickens, weight 1000-2500g. Available fresh and frozen. Certified origin from Polish farms.',
    'product.giblets.title': 'Poultry giblets',
    'product.giblets.desc': 'High-quality giblets: hearts, gizzards, livers, necks. Ideal for further processing.',
    'product.processed.title': 'Eggs',
    'product.processed.desc': 'Fresh eggs from certified farms, available in various classes and sizes. Ideal for consumption and processing.',
    'product.carcasses.title': 'Poultry carcasses',
    'product.carcasses.desc': 'Fresh and frozen poultry carcasses, various weights and packaging. Ideal for further processing and export.',
    'product.drumsticks.title': 'Drumsticks',
    'product.drumsticks.desc': 'Class A chicken drumsticks, available fresh and frozen. Vacuum or MAP packed.',
    'product.cut_feet.title': 'Cut feet',
    'product.cut_feet.desc': 'Cut and sorted poultry feet, mainly exported to Asian markets. Packaging on request.',
    
    // Special Products
    'special.title': 'Special Products on Request',
    'special.subtitle': 'We prepare products according to individual customer specifications. We offer private label services and packaging compliant with the requirements of target markets.',
    'special.production.title': 'Own Production Lines',
    'special.production.desc': 'Modern plants with EU certificates',
    'special.private.title': 'Private Label',
    'special.private.desc': 'Products under the client\'s brand',
    'special.export.title': 'Export Worldwide',
    'special.export.desc': 'Deliveries to 40+ countries',
    'special.cta': 'Download the full product catalog (PDF)',
    
    // Quality Section
    'quality.title': 'Highest Quality Standards',
    'quality.description': 'Our philosophy is based on strict adherence to the highest standards of quality and food safety. We work only with certified farms and plants that meet strict European requirements.',
    'quality.control.title': 'Control at every stage',
    'quality.control.desc': 'From farm to final product - multi-level quality control',
    'quality.lab.title': 'Own laboratories',
    'quality.lab.desc': 'Microbiological and chemical tests in accredited laboratories',
    'quality.cold.title': 'Cold supply chain',
    'quality.cold.desc': 'Uninterrupted cold chain from slaughter to end customer',
    'quality.trace.title': 'Origin tracking',
    'quality.trace.desc': 'Full traceability - from farm to store shelf',
    'quality.guarantee': '100% Safety',
    'quality.guarantee.sub': 'Highest quality guarantee',
    
    // Certifications
    'cert.title': 'Certificates and Accreditations',
    'cert.subtitle': 'We have all the necessary certificates and accreditations required for the export of poultry products. Our plants are regularly inspected by Polish and international certification bodies.',
    'cert.haccp.desc': 'Hazard analysis and critical control points system compliant with EU requirements',
    'cert.iso.desc': 'International food safety management system standard',
    'cert.gap.desc': 'Global standards of good agricultural and farming practice',
    'cert.ifs.desc': 'International Featured Standards for food safety and quality',
    'cert.additional.title': 'Additional Export Certificates',
    'cert.vet.title': 'Veterinary Certificate',
    'cert.vet.desc': 'Issued by PIW for each export batch',
    'cert.halal.title': 'Halal Certification',
    'cert.halal.desc': 'Certification for Muslim markets',
    'cert.eu.title': 'EU Health Certificate',
    'cert.eu.desc': 'Health certificate for export within the EU',
    
    // About Section
    'about.title': 'Leader in Polish Poultry Export',
    'about.description1': 'Masovia Poultry is a leading exporter of Polish poultry with over 20 years of experience in the international market. We are proud that Polish poultry is recognized worldwide thanks to our work and commitment.',
    'about.description2': 'We cooperate with the largest retail chains in Europe, Asia, and the Middle East. Our products reach stores in Germany, France, the UK, the Netherlands, Balkan countries, and Asian markets.',
    'about.stats.tons': 'tons per year',
    'about.stats.countries': 'export countries',
    'about.stats.clients': 'satisfied clients',
    'about.stats.delivery': 'on-time deliveries',
    'about.cta': 'See our story',
    'about.company': 'Masovia Poultry',
    'about.tagline': 'Polish premium poultry since 2004',
    'about.subtitle': 'Export worldwide',
    
    // Contact Section
    'contact.title': 'Start Cooperation',
    'contact.subtitle': 'Contact us today and receive a personalized offer tailored to your needs. Our team of experts will answer all your questions and help you choose the best products.',
    'contact.badge.response': 'Response within 24h',
    'contact.badge.samples': 'Free samples',
    'contact.badge.prices': 'Competitive prices',
    'contact.info.title': 'Contact details',
    'contact.phone.title': 'Phone',
    'contact.phone.export': '+48 516 827 115 (Export Manager)',
    'contact.phone.sales': '+48 987 654 321 (Sales Director)',
    'contact.email.title': 'Email',
    'contact.address.title': 'Headquarters',
    'contact.address.street': 'ul. Przemysłowa 15',
    'contact.address.city': '05-800 Pruszków, Poland',
    'contact.hours.title': 'Working hours',
    'contact.hours.weekdays': 'Monday - Friday: 8:00 - 18:00',
    'contact.hours.saturday': 'Saturday: 9:00 - 14:00',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.hours.urgent': 'For urgent export matters, we are available 24/7',
    
    // CTA Section
    'cta.title': 'Join Our Partners',
    'cta.subtitle': 'We cooperate with the largest importers, retail chains, and processing plants in Europe. Polish premium poultry is a guarantee of success in your market.',
    'cta.tesco': 'Retail chain - UK',
    'cta.auchan': 'Hypermarkets - Europe',
    'cta.metro': 'Cash & Carry - EMEA',
    'cta.special_offer': 'Get a special offer',
    'cta.meeting': 'Arrange a business meeting',
    
    // Footer
    'footer.tagline': 'Leading exporter of the highest quality Polish poultry to international markets.',
    'footer.company_info': 'Polish premium poultry since 2004',
    'footer.products.title': 'Products',
    'footer.products.breast': 'Chicken breast',
    'footer.products.wings': 'Chicken wings',
    'footer.products.quarters': 'Chicken quarters',
    'footer.products.whole': 'Whole chicken',
    'footer.products.giblets': 'Poultry giblets',
    'footer.products.processed': 'Processed products',
    'footer.company.title': 'Company',
    'footer.company.about': 'About us',
    'footer.company.history': 'Company history',
    'footer.company.certificates': 'Quality certificates',
    'footer.company.farms': 'Our farms',
    'footer.company.career': 'Career',
    'footer.company.news': 'News',
    'footer.contact.title': 'Contact',
    'footer.copyright': '© 2024 Masovia Poultry. All rights reserved. | Polish premium poultry | Export worldwide',

    // Product Features
    'product.whole_chicken.feature1': 'Weight 1-2.5kg',
    'product.whole_chicken.feature2': 'Class A premium',
    'product.whole_chicken.feature3': 'Own farms',
    'product.whole_chicken.feature4': 'Certificate of origin',
    'product.carcasses.feature1': 'Fresh and frozen carcasses',
    'product.carcasses.feature2': 'Various weights',
    'product.carcasses.feature3': 'Vacuum packaging',
    'product.carcasses.feature4': 'Certified origin',
    'product.processed.feature1': 'Fresh eggs',
    'product.processed.feature2': 'Various classes and sizes',
    'product.processed.feature3': 'Certified farms',
    'product.processed.feature4': 'Ideal for consumption and processing',
    'product.chicken_breast.feature1': 'Antibiotic-free',
    'product.chicken_breast.feature2': 'Class A',
    'product.chicken_breast.feature3': 'Vacuum packaging',
    'product.chicken_breast.feature4': 'Top quality',
    'product.chicken_wings.feature1': 'Various cuts',
    'product.chicken_wings.feature2': 'Fresh and frozen',
    'product.chicken_wings.feature3': 'Packages from 1kg to 15kg',
    'product.chicken_wings.feature4': 'Various weights',
    'product.chicken_quarters.feature1': 'Upper and lower',
    'product.chicken_quarters.feature2': 'Various weights',
    'product.chicken_quarters.feature3': 'MAP packaging',
    'product.chicken_quarters.feature4': 'Long shelf life',
    'product.whole_chicken.feature1': 'Weight 1-2.5kg',
    'product.whole_chicken.feature2': 'Class A premium',
    'product.whole_chicken.feature3': 'Own farms',
    'product.whole_chicken.feature4': 'Certificate of origin',
    'product.giblets.feature1': 'Hearts, gizzards, livers',
    'product.giblets.feature2': 'Fresh and frozen',
    'product.giblets.feature3': 'Veterinary control',
    'product.giblets.feature4': 'Packaging on request',
    'product.processed.feature1': 'Fresh eggs',
    'product.processed.feature2': 'Various classes and sizes',
    'product.processed.feature3': 'Certified farms',
    'product.processed.feature4': 'Ideal for consumption and processing',
    'product.carcasses.feature1': 'Fresh and frozen carcasses',
    'product.carcasses.feature2': 'Various weights',
    'product.carcasses.feature3': 'Vacuum packaging',
    'product.carcasses.feature4': 'Certified origin',
    'product.drumsticks.feature1': 'Class A chicken drumsticks',
    'product.drumsticks.feature2': 'MAP packaging',
    'product.drumsticks.feature3': 'Available fresh and frozen',
    'product.drumsticks.feature4': 'Various weights',
    'product.cut_feet.feature1': 'Cut and sorted feet',
    'product.cut_feet.feature2': 'Ideal for processing',
    'product.cut_feet.feature3': 'Packaging on request',
    'product.cut_feet.feature4': 'Fresh and frozen',
  },
  ar: {
    // Header
    'nav.products': 'المنتجات',
    'nav.about': 'من نحن',
    'nav.quality': 'الجودة',
    'nav.certificates': 'الشهادات',
    'nav.contact': 'اتصل بنا',
    'nav.download_price': 'اتصل بنا',
    // Hero Section
    'hero.badge': 'المصدر الرائد في بولندا',
    'hero.title': 'دواجن بولندية',
    'hero.title_highlight': 'أعلى جودة',
    'hero.description': 'نحن متخصصون في تصدير لحوم الدواجن الطازجة والمجمدة. نقدم منتجات عالية الجودة لأكبر سلاسل البيع بالتجزئة والمصانع والمستوردين في أكثر من 40 دولة حول العالم.',
    'hero.cta_offer': 'اطلب السعر',
    'hero.cta_phone': '+48 516 827 115',
    'hero.stats.years': 'سنوات الخبرة',
    'hero.stats.countries': 'دول التصدير',
    'hero.stats.tons': 'طن سنوياً',
    'hero.stats.satisfaction': 'عملاء راضون',
    // Benefits Section
    'benefits.title': 'لماذا نحن؟',
    'benefits.subtitle': 'نحن رواد في تصدير الدواجن البولندية بفضل خبرتنا وأعلى معايير الجودة',
    'benefits.quality.title': 'رقابة جودة شاملة',
    'benefits.quality.desc': 'رقابة HACCP صارمة في كل مرحلة من مراحل الإنتاج. مختبراتنا الخاصة.',
    'benefits.delivery.title': 'دقة المواعيد في التسليم',
    'benefits.delivery.desc': 'نضمن التسليم حسب الجدول الزمني. أسطول نقل خاص.',
    'benefits.team.title': 'فريق ذو خبرة',
    'benefits.team.desc': 'فريق من الخبراء مع خبرة 20 سنة في تصدير الدواجن.',
    'benefits.price.title': 'أسعار تنافسية',
    'benefits.price.desc': 'أفضل الأسعار مع الحفاظ على أعلى جودة للمنتجات.',
    // Products Section
    'products.title': 'تشكيلة الدواجن الكاملة',
    'products.subtitle': 'نقدم مجموعة كاملة من منتجات الدواجن - من اللحوم الطازجة إلى المنتجات المصنعة. جميع المنتجات من موردين معتمدين وتتم معالجتها وفقًا لأعلى معايير الاتحاد الأوروبي.',
    'products.badge.fresh': 'لحم طازج',
    'products.badge.frozen': 'منتجات مجمدة',
    'products.badge.processed': 'مصنعات',
    'products.badge.private': 'علامة خاصة',
    // Product Cards
    'product.chicken_breast.title': 'صدر دجاج بدون عظم',
    'product.chicken_breast.desc': 'فيليه ممتاز بدون عظم أو جلد. متوفر بأوزان مختلفة: 140-200 جم، 200-300 جم، أكثر من 300 جم. معبأ بتفريغ الهواء.',
    'product.chicken_wings.title': 'أجنحة الدجاج',
    'product.chicken_wings.desc': 'أجنحة طازجة بأشكال مختلفة: كاملة، مقطعة، مفاصل وسطى، دراميتس. فئات وزن مختلفة.',
    'product.chicken_quarters.title': 'أجنحة الدجاج',
    'product.chicken_quarters.desc': 'أجنحة الدجاج الطازجة بأشكال مختلفة: كاملة، مقطعة، مفاصل وسطى، دراميتس. فئات وزن مختلفة.',
    'product.whole_chicken.title': 'كتاب الدجاج',
    'product.whole_chicken.desc': 'كتاب الدجاج الكامل، وزن 1000-2500 جم. متوفر طازج ومجمد. صفة التصنيع موثقة من المزارع البولندية.',
    'product.giblets.title': 'أجنحة الدجاج',
    'product.giblets.desc': 'أجنحة الدجاج الكاملة، وزن 1000-2500 جم. متوفر طازج ومجمد. صفة التصنيع موثقة من المزارع البولندية.',
    'product.processed.title': 'بيض الدجاج',
    'product.processed.desc': 'بيض الدجاج الطازج، متوفر بأنواع مختلفة وأحجام. مثالي للاستهلاك والتحويل.',
    'product.carcasses.title': 'جسم الدجاج',
    'product.carcasses.desc': 'جسم الدجاج الطازج والمجمد، وأوزان وتغليف مختلف. مثالي للتحويل والتصدير.',
    'product.drumsticks.title': 'دراميتس الدجاج',
    'product.drumsticks.desc': 'دراميتس الدجاج الكامل، متوفر طازج ومجمد. تغليف أو MAP.',
    'product.cut_feet.title': 'أطراف الدجاج',
    'product.cut_feet.desc': 'أطراف الدجاج المقطوعة والمصنفة، تصدر أساساً إلى الآسيا. تغليف على طلب.',
    
    // Special Products
    'special.title': 'منتجات خاصة على الطلب',
    'special.subtitle': 'نحن نصنع منتجات حسب المواصفات الفردية لعملائنا. نقدم خدمات العلامة الخاصة وتغليف متطابق مع متطلبات السوق المستهدف.',
    'special.production.title': 'خطوط إنتاج خاصة',
    'special.production.desc': 'مصانع حديثة بشهادات الاتحاد الأوروبي',
    'special.private.title': 'العلامة الخاصة',
    'special.private.desc': 'منتجات تحت علامة العميل',
    'special.export.title': 'تصدير عالمي',
    'special.export.desc': 'توفير في أكثر من 40 دولة',
    'special.cta': 'تحميل كتالوج المنتجات بصيغة PDF',
    
    // Quality Section
    'quality.title': 'أعلى معايير الجودة',
    'quality.description': 'فلسفتنا تعتمد على مبدأ التقدير المطلق لأعلى معايير الجودة وسلامة الغذاء. نعمل مع المزارع والمصانع المعتمدين فقط الذين يلبين متطلبات الاتحاد الأوروبي الصارمة.',
    'quality.control.title': 'التحكم في كل مرحلة',
    'quality.control.desc': 'من المزرعة إلى المنتج النهائي - التحكم بجودة المستوى المتعدد',
    'quality.lab.title': 'مختبرات خاصة',
    'quality.lab.desc': 'تحاليل طبيعية وكيميائية في مختبرات معتمدة',
    'quality.cold.title': 'سلسلة التبريد',
    'quality.cold.desc': 'سلسلة التبريد غير متوقفة عن التدفق من التسليم إلى العميل النهائي',
    'quality.trace.title': 'تتبع المصدر',
    'quality.trace.desc': 'تتبع كامل - من المزرعة إلى مكان البيع',
    'quality.guarantee': '100% سلامة',
    'quality.guarantee.sub': 'ضمان أعلى جودة',
    
    // Certifications
    'cert.title': 'شهادات وتراخيص',
    'cert.subtitle': 'لدينا جميع الشهادات والتراخيص اللازمة لتصدير الدواجن. مصانعنا مراقبة بشكل دوري من قبل مؤسسات التصدير البولندية والدولية.',
    'cert.haccp.desc': 'نظام تحليل المخاطر والنقاط الحرجة للتحكم المتطابق مع متطلبات الاتحاد الأوروبي',
    'cert.iso.desc': 'معيار بين المؤسسات لإدارة السلامة الغذائية',
    'cert.gap.desc': 'معايير عالمية للممارسات الزراعية والتربية',
    'cert.ifs.desc': 'معايير متميزة متاحة للسلامة والجودة في الغذاء',
    'cert.additional.title': 'شهادات تصدير إضافية',
    'cert.vet.title': 'شهادة طبيب الدواجن',
    'cert.vet.desc': 'منحت بواسطة PIW لكل حصة من التصدير',
    'cert.halal.title': 'شهادة Halal',
    'cert.halal.desc': 'شهادة للأسواق المسلمة',
    'cert.eu.title': 'شهادة صحية UE',
    'cert.eu.desc': 'شهادة صحية للتصدير داخل الاتحاد الأوروبي',
    
    // About Section
    'about.title': 'مصدر التصدير البولندي للدواجن',
    'about.description1': 'Masovia Poultry هو مصدر رائد للدواجن البولندية بفضل خبرتنا وأعلى معايير الجودة على المستوى الدولي. نحن فخورون بأن الدواجن البولندية تحظى بتعريف على المستوى العالمي بفضل عملنا وتأييدنا.',
    'about.description2': 'نحن نصنع منتجات حسب المواصفات الفردية لعملائنا. نقدم خدمات العلامة الخاصة وتغليف متطابق مع متطلبات السوق المستهدف.',
    'about.stats.tons': 'طن سنوياً',
    'about.stats.countries': 'دول التصدير',
    'about.stats.clients': 'عملاء راضون',
    'about.stats.delivery': 'دقة المواعيد في التسليم',
    'about.cta': 'نحن نصنع منتجات حسب المواصفات الفردية لعملائنا. نقدم خدمات العلامة الخاصة وتغليف متطابق مع متطلبات السوق المستهدف.',
    'about.company': 'Masovia Poultry',
    'about.tagline': 'دواجن بولندية premium من 2004',
    'about.subtitle': 'تصدير عالمي',
    
    // Contact Section
    'contact.title': 'اتصال',
    'contact.subtitle': 'اتصل بنا اليوم واحصل على عرض شخصي مطابق لاحتياجاتك. فريقنا من الخبراء سيجيب على جميع أسئلتك ويساعدك على اختيار أفضل المنتجات.',
    'contact.badge.response': 'رد في 24 ساعة',
    'contact.badge.samples': 'عينات مجانية',
    'contact.badge.prices': 'أسعار منافسة',
    'contact.info.title': 'تفاصيل الاتصال',
    'contact.phone.title': 'الهاتف',
    'contact.phone.export': '+48 516 827 115 (مدير التصدير)',
    'contact.phone.sales': '+48 987 654 321 (مدير المبيعات)',
    'contact.email.title': 'البريد الإلكتروني',
    'contact.address.title': 'المقر الرئيسي',
    'contact.address.street': 'شارع الصناعي 15',
    'contact.address.city': '05-800 Pruszków, Polska',
    'contact.hours.title': 'ساعات العمل',
    'contact.hours.weekdays': 'الاثنين - الجمعة: من 8:00 إلى 18:00',
    'contact.hours.saturday': 'السبت: من 9:00 إلى 14:00',
    'contact.hours.sunday': 'الأحد: مغلق',
    'contact.hours.urgent': 'للأعمال التصديرية الحالية، نحن متاحون 24/7',
    
    // CTA Section
    'cta.title': 'إنضم إلى شريكنا',
    'cta.subtitle': 'نحن نصنع منتجات حسب المواصفات الفردية لعملائنا. نقدم خدمات العلامة الخاصة وتغليف متطابق مع متطلبات السوق المستهدف.',
    'cta.tesco': 'سلسلة توزيع - UK',
    'cta.auchan': 'ماركت الهايبر - أوروبا',
    'cta.metro': 'كاش فالي - أوروبا',
    'cta.special_offer': 'احصل على عرض خاص',
    'cta.meeting': 'إقامة اجتماع تجاري',
    
    // Footer
    'footer.tagline': 'مصدر التصدير البولندي للدواجن الكاملة من أعلى الجودة إلى الأسواق الدولية.',
    'footer.company_info': 'دواجن بولندية premium من 2004',
    'footer.products.title': 'المنتجات',
    'footer.products.breast': 'صدر دجاج بدون عظم',
    'footer.products.wings': 'أجنحة الدجاج',
    'footer.products.quarters': 'أجنحة الدجاج',
    'footer.products.whole': 'كتاب الدجاج',
    'footer.products.giblets': 'أجنحة الدجاج',
    'footer.products.processed': 'بيض الدجاج',
    'footer.company.title': 'الشركة',
    'footer.company.about': 'من نحن',
    'footer.company.history': 'تاريخ الشركة',
    'footer.company.certificates': 'شهادات الجودة',
    'footer.company.farms': 'مزارعنا',
    'footer.company.career': 'المهندسين',
    'footer.company.news': 'الأخبار',
    'footer.contact.title': 'اتصال',
    'footer.copyright': '© 2024 Masovia Poultry. جميع الحقوق محفوظة. | الدواجن البولندية premium | تصدير عالمي',

    // Product Features
    'product.whole_chicken.feature1': 'وزن 1-2.5كجم',
    'product.whole_chicken.feature2': 'فئة A premium',
    'product.whole_chicken.feature3': 'مزارع خاصة',
    'product.whole_chicken.feature4': 'شهادة المنشأ',
    'product.carcasses.feature1': 'جسم الدجاج الطازج والمجمد',
    'product.carcasses.feature2': 'أوزان مختلفة',
    'product.carcasses.feature3': 'تغليف تفريغ الهواء',
    'product.carcasses.feature4': 'صفة التصنيع موثقة',
    'product.processed.feature1': 'بيض طازج',
    'product.processed.feature2': 'أنواع مختلفة وأحجام',
    'product.processed.feature3': 'مصانع معتمدة',
    'product.processed.feature4': 'مثالي للاستهلاك والتحويل',
    'product.chicken_breast.feature1': 'بدون مضادات حيوية',
    'product.chicken_breast.feature2': 'الفئة A',
    'product.chicken_breast.feature3': 'تغليف مفرغ من الهواء',
    'product.chicken_breast.feature4': 'أعلى جودة',
    'product.chicken_wings.feature1': 'تقطيع متنوع',
    'product.chicken_wings.feature2': 'طازجة ومجمدة',
    'product.chicken_wings.feature3': 'عبوات من 1كجم إلى 15كجم',
    'product.chicken_wings.feature4': 'أوزان مختلفة',
    'product.chicken_quarters.feature1': 'العلوية والسفلية',
    'product.chicken_quarters.feature2': 'أوزان مختلفة',
    'product.chicken_quarters.feature3': 'تغليف MAP',
    'product.chicken_quarters.feature4': 'مدة صلاحية طويلة',
    'product.whole_chicken.feature1': 'وزن 1-2.5كجم',
    'product.whole_chicken.feature2': 'الفئة A بريميوم',
    'product.whole_chicken.feature3': 'مزارع خاصة',
    'product.whole_chicken.feature4': 'شهادة المنشأ',
    'product.giblets.feature1': 'قلوب، قوانص، أكباد',
    'product.giblets.feature2': 'طازجة ومجمدة',
    'product.giblets.feature3': 'رقابة بيطرية',
    'product.giblets.feature4': 'تغليف حسب الطلب',
    'product.processed.feature1': 'بيض طازج',
    'product.processed.feature2': 'أنواع وأحجام مختلفة',
    'product.processed.feature3': 'مزارع معتمدة',
    'product.processed.feature4': 'مثالي للاستهلاك والمعالجة',
    'product.carcasses.feature1': 'جثث طازجة ومجمدة',
    'product.carcasses.feature2': 'أوزان مختلفة',
    'product.carcasses.feature3': 'تغليف مفرغ من الهواء',
    'product.carcasses.feature4': 'منشأ معتمد',
    'product.drumsticks.feature1': 'أفخاذ دجاج فئة A',
    'product.drumsticks.feature2': 'تغليف MAP',
    'product.drumsticks.feature3': 'متوفر طازج ومجمد',
    'product.drumsticks.feature4': 'أوزان مختلفة',
    'product.cut_feet.feature1': 'أقدام مقطعة ومصنفة',
    'product.cut_feet.feature2': 'مثالية للمعالجة',
    'product.cut_feet.feature3': 'تغليف حسب الطلب',
    'product.cut_feet.feature4': 'طازجة ومجمدة',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Helper to get initial language
  const getInitialLanguage = (): Language => {
    // 1. Check localStorage
    const stored = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
    if (stored && ['pl', 'fr', 'it', 'en', 'ar'].includes(stored)) {
      return stored as Language;
    }
    // 2. Check browser language
    if (typeof navigator !== 'undefined') {
      const browserLang = navigator.language.slice(0, 2);
      if (['pl', 'fr', 'it', 'en', 'ar'].includes(browserLang)) {
        return browserLang as Language;
      }
    }
    // 3. Default to 'pl'
    return 'pl';
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  // Persist language to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
