name: Deploy to GitHub Pages (development branch root)

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Copy dist to root
        run: |
          shopt -s dotglob
          cp -r dist/* .
      - name: Commit and push built files to development branch root
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: deploy built static site to branch root [skip ci]" || echo "No changes to commit"
          git push origin development 